services:
  - type: web
    name: swgoh-arena-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
